# Generated by Django 4.2.4 on 2023-09-20 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_place1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place1',
            old_name='description',
            new_name='description1',
        ),
        migrations.RenameField(
            model_name='place1',
            old_name='image',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='place1',
            old_name='name',
            new_name='name1',
        ),
    ]
